import type { CheckService } from "../checks/CheckService";
import type { AppSnapshot } from "../dashboard/types";
import type { AppEventLog } from "../events/AppEventLog";
import type { EventStore } from "../events/EventStore";
import type { GitService } from "../git/GitService";
import type { ObservabilityService } from "../observability/ObservabilityService";
import type { PolicyService } from "../policies/PolicyService";
import type { PluginRegistry } from "../plugins/PluginRegistry";
import type { ProjectRegistryService } from "../projects/ProjectRegistryService";
import type { SettingsService } from "../settings/SettingsService";
import type { AgentRunService, ArtifactService, ProjectWorkspaceService, WorkItemService } from "./ProjectWorkspaceService";
import type { ProviderRegistry } from "./ProviderRegistry";
import type { ProviderService } from "./ProviderService";

export type PraxisRuntime = {
  events: AppEventLog;
  eventStore: EventStore;
  providerRegistry: ProviderRegistry;
  providers: ProviderService;
  workspace: ProjectWorkspaceService;
  workItems: WorkItemService;
  artifacts: ArtifactService;
  agentRuns: AgentRunService;
  projects: ProjectRegistryService;
  git: GitService;
  checks: CheckService;
  policies: PolicyService;
  observability: ObservabilityService;
  plugins: PluginRegistry;
  settings: SettingsService;
  snapshot(): AppSnapshot;
  restore(): Promise<AppSnapshot>;
  replay(): Promise<AppSnapshot>;
};
